version: '3.5'
networks:
  default:
    name: default-network
services:
  bff:
    build:
      context: ./api/src/bff-mobile
    environment:
      - GRAPHQL_ENDPOINT
      - CONFIGURATION_ENDPOINT
    ports:
      - "8081:8000"
    stdin_open: true
    tty: true
  graphql-api:
    build:
      context: ./graphql-api
    environment:
      - MOVIE_DB_ENDPOINT
      - CONFIGURATION_ENDPOINT
      - API_KEY
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
  nginx:
    build:
      context: ./nginx
      dockerfile: ./purge-enabled/Dockerfile
    environment:
      # TODO inject properly via env
      - BFF_ENDPOINT=http://bff:8000 
    ports:
      - "8080:8000"
    # stdin_open: true
    # tty: true


